# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Thundra From Master

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'     
        required: true
        default: 'main'
  schedule:
    - cron: 0 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THUNDRA_APIKEY: ${{ secrets.THUNDRA_APIKEY }}
      THUNDRA_AGENT_REPORT_REST_BASEURL: https://api-lab.thundra.io/v1
      THUNDRA_AGENT_APPLICATION_NAME: spring-boot
      THUNDRA_AGENT_BROKER_ENABLE: falsejs
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Rebase From Origin
      run: ./repo-watcher rebase
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
